// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0hHAqxZpbSTuc6ghJGmy7KkxBwalnRmg',
    appId: '1:1037039845782:web:619cfcb431483b28e71db7',
    messagingSenderId: '1037039845782',
    projectId: 'adai-431f8',
    authDomain: 'adai-431f8.firebaseapp.com',
    storageBucket: 'adai-431f8.firebasestorage.app',
    measurementId: 'G-WN8GBTLH28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1vSx3ofJyJPmrpxiFMN0KHJZdaME470',
    appId: '1:1037039845782:android:09a5ed37258f0e20e71db7',
    messagingSenderId: '1037039845782',
    projectId: 'adai-431f8',
    storageBucket: 'adai-431f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB68h4UBCY6msDJY0Rr0jlcO0uB3pZyq9o',
    appId: '1:1037039845782:ios:e08dd46d6cb08611e71db7',
    messagingSenderId: '1037039845782',
    projectId: 'adai-431f8',
    storageBucket: 'adai-431f8.firebasestorage.app',
    iosBundleId: 'com.example.adai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB68h4UBCY6msDJY0Rr0jlcO0uB3pZyq9o',
    appId: '1:1037039845782:ios:e08dd46d6cb08611e71db7',
    messagingSenderId: '1037039845782',
    projectId: 'adai-431f8',
    storageBucket: 'adai-431f8.firebasestorage.app',
    iosBundleId: 'com.example.adai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0hHAqxZpbSTuc6ghJGmy7KkxBwalnRmg',
    appId: '1:1037039845782:web:0a4c3ea3af47f41be71db7',
    messagingSenderId: '1037039845782',
    projectId: 'adai-431f8',
    authDomain: 'adai-431f8.firebaseapp.com',
    storageBucket: 'adai-431f8.firebasestorage.app',
    measurementId: 'G-MYML1FP7T0',
  );
}
